[package]
name = "megastore_search_system"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
lazy_static = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
[lib]
name = "megastore_search_system"
path = "src/lib.rs"
